version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/src/terraform"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
